### ISSUE TITLE
"Play offline" option

### ISSUE THREAD

**Issue by jan-kleks** [KyleU/solitaire.gg#11]
I don't know if it is technically possible, but it would be nice to have an option "Play offline" which would download every single solitaire, and as long as you won't clear cache (or whatever it is you store the game data in) you should be able to basically play offline.

Such an option would work very nicely with the ["Add to Home Screen" button](https://github.com/KyleU/solitaire.gg/issues/10#issue-218793348) on iOS.

**Comment by KyleU** [comment]
I actually built an app for both Android and iOS, but keeping them up to date was a hassle, and it's impossible to get up in the store rankings without a marketing budget.

https://itunes.apple.com/is/app/solitaire.gg/id1056989640?mt=8
https://play.google.com/store/apps/details?id=gg.solitaire&hl=en

**Comment by jan-kleks** [comment]
Oh, I didn't know about Android and iOS apps. Well, you can always bring them back when you will such a need. BTW, I've learned that solitaire.gg exists here: http://alternativeto.net/software/solitaire-gg/

Yeah, but I actually meant offline mode directly in a browser and not separate apps. If it is not possible, mark the issue as "wontfix", please.

**Comment by KyleU** [comment]
Once I restore the desktop and mobile apps, they will suffice for pure offline mode. The web version will still need a connection to initially load, but you'll be able to use the full functionality even if your connection is broken (thanks, Scala.js).

**Comment by lhaig** [comment]
Any ETA for the offline client for Windows?
My Mom and Dad are running on Windows and since windows updated to require logins and subscription to play their solitair etc. I was looking for something else for them.
I am no coder and I have been trying to see how to build solitaire.gg for electron for them but I have not been successful.
Do you have some instructions on how to do this ? I and my parents would appreciate it.

**Comment by jan-kleks** [comment]
@lhaig Kyle is currently in the process of adding many new features to solitaire.gg (you may find the current beta version at http://beta.solitaire.gg), so I guess offline versions will come some time after he finishes that task. If you have any suggestions for improving solitaire.gg, you're welcome to create new issue tickets.

In the meantime, if you really need a good offline solitaire collection check out [PySolFC](https://github.com/shlomif/PySolFC). You can use the built-in Windows Magnifier to make everything larger for your parents.

**Comment by KyleU** [comment]
Yep, I'm restoring the apps and desktop builds tonight. I had removed them since no one ever used them, but there's apparently a demand, so I'll package them up as soon as I can.

**Comment by lhaig** [comment]
Guys thanks for this.
I do appreciate response. 
Kyle if i need to buy a license for this I will.
My mom has dementia and so finding something she can play is difficult as she remembers xp only at the moment.
Thanks for doing this.
