### ISSUE TITLE
solitaire.gg logo on the main page

### ISSUE THREAD

**Issue by jan-kleks** [KyleU/solitaire.gg#13]
It's such a nice simple logo, maybe it should be present on the main page (https://solitaire.gg/) too.

**Comment by KyleU** [comment]
This will be resolved with the new UI that I'm working on now.

**Comment by KyleU** [comment]
Testable at https://beta.solitaire.gg

**Comment by jan-kleks** [comment]
Yeah, this corner might be a good place for the logo. Mind you, that in the current form, "A" symbols on the smaller version of the logo are so minuscule, that it does not look too nice. Hmm... this problem might affect to some degree this small logo icon that appears in the browser's tab too. But the look of the logo in the app is much more important.

**Comment by jan-kleks** [comment]
I've noticed something strange, these tiny "A" symbols look fine on my iPhone 7, but not in Firefox on my iMac...

**Comment by KyleU** [comment]
New simple-as-possible logo on beta.solitaire.gg, thanks for the feedback!
