### ISSUE TITLE
On iOS allow scrolling for particular content only instead of the whole app window

### ISSUE THREAD

**Issue by jan-kleks** [KyleU/solitaire.gg#15]
If you open "settings" or "rules" on iOS and then start scrolling their content using your finger so that you finally reach the "settings" or "rules" top/bottom window limit, the whole solitaire.gg app starts "moving" which does not look too nice.

I have no idea whether it's possible to block this behavior somehow.

**Comment by KyleU** [comment]
This will be resolved with the new UI that I'm working on now.

**Comment by KyleU** [comment]
Resolved in new UI.
