### ISSUE TITLE
Responsive Playing Cards by Digital Design Labs

### ISSUE THREAD

**Issue by jan-kleks** [KyleU/solitaire.gg#19]
Would this be of any use to you?: https://github.com/digitaldesignlabs/responsive-playing-cards

**Comment by KyleU** [comment]
I think I used them at one point, the SVGs were useful. I'm still using raster assets (though in a crazy high resolution), and rendering the cards dynamically at runtime. I'd love to get some new designs in there, but haven't been able to find many high-quality free(ish) sources.
