### ISSUE TITLE
Use your games in Telegram bot?

### ISSUE THREAD

**Issue by MasterGroosha** [KyleU/solitaire.gg#2]
Hello.
Since Telegram introduced [Gaming Platform](https://telegram.org/blog/games) in 2016, I'm asking for your permission to load games from your site solitaire.gg via my Telegram bot.

I've made a test bot, you can find it in Telegram as [@SolitaireGGbot](https://telegram.me/solitaireggbot). In case you don't have Telegram, here's a video how it works (again: this is just to show you what I'm talking about).
https://yadi.sk/i/ixCZIJIX3FPoky

**Comment by KyleU** [comment]
Absolutely, feel free to embed or share https://solitaire.gg anywhere you'd like!

**Comment by KyleU** [comment]
Also, thanks for including the links and video.

**Comment by MasterGroosha** [comment]
You're welcome!
