### ISSUE TITLE
Background with a simple texture

### ISSUE THREAD

**Issue by jan-kleks** [KyleU/solitaire.gg#20]
A solid color background is not that bad (especially if the color is chosen correctly). You might also think about a simple background texture as an option. But be careful not to choose some  cheap gradient. :P

**Comment by KyleU** [comment]
Agreed - I'm not a designer, so I stuck with minimalism. I had plans to allow user-uploaded backgrounds, but it didn't seem worth the hassle. I can add some curated backgrounds through, maybe loot https://www.toptal.com/designers/subtlepatterns/ - Thanks for the feedback, I'll keep this issue open until better backgrounds get added.

**Comment by jan-kleks** [comment]
Very cool site! Just try to choose simple patterns like this one, for instance: https://www.toptal.com/designers/subtlepatterns/p4/ And not some fancy ones. You can utilize them so that the user would be able to choose a solid color (which is already possible) and then (optionally) put one of these patterns onto this solid color background.

**Comment by jan-kleks** [comment]
It would be also nice if the user could define the color of that texture (white or gray by default?) too.

**Comment by KyleU** [comment]
I looted transparenttextures.com, and added a color picker. Huge improvement, thanks!

https://beta.solitaire.gg/settings

**Comment by jan-kleks** [comment]
Also, you could consider some kind of a **transition effect** when changing textures (now you click on a texture, and a new pattern "suddenly" appears). For instance, the old texture would fade out, and the new one appear in its place.

**Comment by KyleU** [comment]
Cool idea, but probably more effort than it's worth, CSS doesn't let you fade backgrounds easily.

Also, had a question for you. Right now, users default to a blank blue background. I like using the blue, but should probably include a texture by default. What's your favorite?

**Comment by jan-kleks** [comment]
I don't know... Maybe something simple like this one called "vichy", but it's hard to decide. :P Don't forget to mark in some way the option without the texture (it took me some time to actually find it).

**Comment by KyleU** [comment]
Added an "X" to the "no texture" option, changed the default texture.
