### ISSUE TITLE
Three bars in the upper left corner suggest that it's settings menu

### ISSUE THREAD

**Issue by jan-kleks** [KyleU/solitaire.gg#21]
At least in most apps. I'm constantly confusing this with the proper settings icon, i.e. the cog. Maybe you should consider using the classic "rounded repeat arrow" for the new game menu?

**Comment by jan-kleks** [comment]
When fixing this, you can also consider taking these two options "Different Game" and "Redeal" out of the menu and putting them directly on the bar. Users use them very often, why should they click/tap two times to get to them?

**Comment by KyleU** [comment]
I'll add the current link to the top bar as buttons once I find a decent icon.

**Comment by KyleU** [comment]
Resolved in new UI.
