### ISSUE TITLE
Create an address for testing beta features, e.g. beta.solitaire.gg or test.solitaire.gg

### ISSUE THREAD

**Issue by jan-kleks** [KyleU/solitaire.gg#29]
So that users would be able test new features and report bugs during development, and before they will be implemented at stable solitaire.gg

**Comment by KyleU** [comment]
Here's a beta link:

https://solitaire.gg/play

It's all busted right now, can't even play, but it represents a rewrite of the client code, which should make a lot of new changes simpler.

**Comment by KyleU** [comment]
https://beta.solitaire.gg

This is where I'll test new features and fixes. Thanks again for the suggestion!
