### ISSUE TITLE
Remove similar background colors and add custom color selection field

### ISSUE THREAD

**Issue by jan-kleks** [KyleU/solitaire.gg#39]
When it comes to the background color choice in your app, there are quite a few very similar colors. Maybe leave only the most characteristic ones (or these that you subjectively like the most), and add a small field for pasting a hex value for even further customization (I guess a color picker might be too much for your solitaire as you seem to keep this app as simple as it is only possible).

See also: https://github.com/KyleU/solitaire.gg/issues/38

**Comment by jan-kleks** [comment]
You can also point people to the [Google color pick applet](https://www.google.com/search?q=color+pick), if they click on the hex value link.

**Comment by KyleU** [comment]
https://beta.solitaire.gg -> Settings

I added a color picker and a crapload of translucent repeating textures. Thanks for the suggestion, let me know what you think!

**Comment by jan-kleks** [comment]
It's awesome! A few things (it's still "beta", so maybe you can ignore what I'm about to write...):

-- the "pool-table" texture is green, and the "food" texture is beige (err... I guess?), make sure that all the textures are using neutral transparency and not specific colors.

-- as I have said earlier, you might want to try implement separate settings for the background color and the texture color, though I don't know how well this would work in practice...

-- when using the color picker and dragging this little dot, as well as the bar (on the rainbow stripe), the cursor (macOS, latest Firefox) would start to "flicker" between a standard arrow cursor, and the hyperlink hand cursor.

-- hex values would be nice too.

**Comment by KyleU** [comment]
Removed the two textures you mentioned, nice find!

I'm pretty happy with where the theme service is at. I'll add a textbox for a specific hex color. 

I can't fix the flickering icon, that's a bug in the color picker I chose (if there's a better one, let me know).

**Comment by jan-kleks** [comment]
Yeah, with the new color picker, the cursor no longer flickers (though it's a bit strange that it changes into the text cursor). I wanted to draw your attention to one more thing, when using the "rainbow stripe", some "starting" colors are extremely bright, so maybe the starting brightness for colors on the "rainbow stripe" should be lower?
