### ISSUE TITLE
Canfield card stock dealing in solitaire.gg vs PySolFC

### ISSUE THREAD

**Issue by jan-kleks** [KyleU/solitaire.gg#45]
In solitaire.gg if you click on the stock, three cards are dealt, and you can see each of them all the time. However, in PySolFC you can see that three cards are being dealt (and you can see each of the three cards during the quick dealing process), but when the dealing is over you may see only the last card by the stock.

Which of these dealing methods is better/more correct? I have no idea...

**Comment by KyleU** [comment]
I think I prefer the current view-all-three style. While PySol's method saves screen space, there's valuable information in the other cards.
