### ISSUE TITLE
Save system + generate code to export saved game

### ISSUE THREAD

**Issue by jan-kleks** [KyleU/solitaire.gg#55]

**Comment by jan-kleks** [comment]
Also, when switching solitaires, solitaire.gg could ask if you want to save this game.

**Comment by KyleU** [comment]
Not sure I'll implement save/load, but I will keep the most recent game active through page reloads when you're online (most of the client rewrite is to bring back server-side game validation).

**Comment by KyleU** [comment]
Reload-persistence is covered by #54, closing this issue since general save/load is a hard problem (leaderboards, stats, timing, etc).
