### ISSUE TITLE
Use perspective to create pseudo-3D effect

### ISSUE THREAD

**Issue by jan-kleks** [KyleU/solitaire.gg#58]
Even though real 3D makes no sense in solitaires, in my humble opinion, you could use perspective to create an optional pseudo-3D effect, just check which angle would look best.

![image](https://cloud.githubusercontent.com/assets/15075571/25783481/21a4fe26-335d-11e7-8955-f2799f6ba455.png)

**Comment by KyleU** [comment]
I'm eventually going full 3D with VR support, using AFrame, because how awesome would that be? So no perspective view.

**Comment by jan-kleks** [comment]
If you really want to go into this, I guess you're right. :P
