### ISSUE TITLE
Card edges look somewhat "strange"

### ISSUE THREAD

**Issue by jan-kleks** [KyleU/solitaire.gg#59]
I don't know how to describe it precisely, or maybe I'm just too picky, but card edges seem a bit "strange" in your app. Some cards seem to have no edge at all (no black thin line), sometimes this edge seems to be pronounced even too much, pay attention to the right edge of the deck (find a big screen). Maybe I'm hallucinating... :P

**Comment by KyleU** [comment]
I use a very thin border at a large size, so less than 1080p and the border will flicker in and out, since the resized border occupies a less than a pixel. I'm adding resolution-dependent sizes soon, that should fix this. Thanks for the report.

**Comment by KyleU** [comment]
The source of the ugly was non-retina screens pixellating when the cards tilted. I've added an option to disable the card tilt.
