### ISSUE TITLE
Simple sound effects (+ a setting to turn them on/off)

### ISSUE THREAD

**Issue by jan-kleks** [KyleU/solitaire.gg#6]

**Comment by KyleU** [comment]
I've actually got all the code written to play sound effects, including enabling/disabling the option, but everything I found for actual sounds seemed fake and jarring. If you can point me to some decent sound assets, I'll have them integrated in minutes.

**Comment by jan-kleks** [comment]
Hmm... I'm not sure about licenses, but maybe you could use sounds from [the legendary PySolFC project](http://pysolfc.sourceforge.net/)(read below why I think it's "legendary"). Or from stock GNOME or KDE solitaires.

BTW, a developer who goes by the name "shlomif" is trying to [resurrect PySolFC and make it compatible with modern systems](https://github.com/shlomif/PySolFC/). I think that PySolFC is "legendary" because it is an open-source collection of over 1000 (!) solitaire card (and not only) games with a lot useful features such as advanced stats and analysis tools. You should definitely check it out even though it does not look (graphically) nice today. 

Maybe you could share some code or work together with shlomif in some way?

**Comment by KyleU** [comment]
Wow, if I'd seen that a few years ago, I would have totally used it. Instead, I found politaire.com, and used their game definitions.

I'll look into using PySolFC's sounds (and maybe more)! The GPL license would have been a problem when I was getting started, but now that it's open source (allowing awesome comments like yours), I'd consider changing to GPL.

**Comment by jan-kleks** [comment]
Hmm... I'm not sure that solitaire.gg needs music, but you can check the PySolFC soundtrack (GPL license) by Carl "Nightbeat" Larsson anyway. To be honest, PySolFC's music is what made me like this app in the first place. :) It's calm, peaceful, and works very well together with other PySolFC sound samples.

**Comment by jan-kleks** [comment]
You use CTRL+U in PySolFC to change tracks.

**Comment by KyleU** [comment]
Added some basic sounds from opengameart. They're turned off by default, but available in the settings for https://beta.solitaire.gg.

**Comment by jan-kleks** [comment]
Should I hear anything already? No sound in both dekstop and mobile Safari even after turning it on.

**Comment by KyleU** [comment]
Right you are, doesn't seem to work in Safari at all. Chrome and Firefox work fine, I'll dig in and figure it out.
