### ISSUE TITLE
Bug with Pyramid 

### ISSUE THREAD

**Issue by topwebstudio** [KyleU/solitaire.gg#61]
I'm attaching video on how to reproduce it, the error log and a screenshot.

[bug.zip](https://github.com/KyleU/solitaire.gg/files/1571719/bug.zip)

**Comment by KyleU** [comment]
Thanks for the detailed report, I'll get it fixed up tonight!

**Comment by topwebstudio** [comment]
Seems to work after https://github.com/KyleU/solitaire.gg/commit/ae3ec5d9d122c4159efb56287e5ebea1fc97a45e
