### ISSUE TITLE
gauge

### ISSUE THREAD

**Issue by numericlee** [KyleU/solitaire.gg#64]
Kyle, thanks so much for posting this program. I am having trouble with the Gauge dependency
New to Scala, running in Windows 10 on Intellij IDE

_Initially I got_
> Error running 'Specifications': Cannot run program "gauge" (in directory 

> "C:\Users\NumericLee\IdeaProjects\solitaire.gg-master\.idea\modules"): CreateProcess error=2, The system cannot find the file specified

_I tried downloading gauge but it wont import_

> "C:/Program Files/Gauge/bin/gauge.exe" run --machine-readable --hide-suggestion --simple-console C:\Users\NumericLee\IdeaProjects\solitaire.gg-master\specs
> Failed to find project directory

I tried creating a subfolder with the name
**C:\Users\NumericLee\IdeaProjects\solitaire.gg-master\specs**
still no success

**Comment by KyleU** [comment]
Never heard of a program named `gauge`, looks like it's a testing tool. If you didn't intend to enable that plugin, removing it might fix the issue. Let me know if you rely on gauge, and I'll try to test locally.

https://plugins.jetbrains.com/plugin/7535-gauge

**Comment by numericlee** [comment]
thanks, was able to remove gauge
