### ISSUE TITLE
Update Phaser.io to 3.x

### ISSUE THREAD

**Issue by topwebstudio** [KyleU/solitaire.gg#68]
Phaser 3 has lots of improvements over the version 2 branch, amongs which is SVG support.
If implemented this could be bye bye for the PNG graphics.
Current version is **3.5** and it has rapid release cycle.

![phaser-340-released](https://user-images.githubusercontent.com/1667635/38866856-ea655598-424a-11e8-96c2-db0e557786ae.png)

**Comment by KyleU** [comment]
Yep, I'm really excited for Phaser 3, but the new APIs make it a complicated upgrade, particularly since there's not any JavaScript in solitaire.gg, it's all Scala.js, and the bindings aren't available for Phaser 3 yet (I'm the guy that builds those, and it'll be a full day or two of work).
