### ISSUE TITLE
Is this written with the Phaser framework?

### ISSUE THREAD

**Issue by spencerthayer** [KyleU/solitaire.gg#72]
Phaser seems to think your source was written with their framework https://phaser.io/news/2016/04/solitaire however it looks like this is written in Scala.

**Comment by KyleU** [comment]
It is indeed based on Phaser, a tremendous engine! However, the client code is written in Scala, and compiled to JavaScript by Scala.js. It's a great community built around a strong language.

https://www.scala-js.org
